# Generated by Django 3.1.4 on 2020-12-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
